# Please see the documentation for all configuration options: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    target-branch: main
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ":seedling:"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"

  # 2. Backend Dependencies
  # Looks for package.json in the backend folder
  - package-ecosystem: "npm"
    directory: "/app/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    target-branch: main
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "eslint"
        versions:
          - ">=10.0.0 <11.0.0"
      - dependency-name: "@eslint/js"
        versions:
          - ">=10.0.0 <11.0.0"
    commit-message:
      prefix: ":robot:"
      include: "scope"
    labels:
      - "dependencies"
      - "nodejs"
      - "backend"

  # 3. Frontend Dependencies
  # Looks for package.json in the client folder
  - package-ecosystem: "npm"
    directory: "/app/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    target-branch: main
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "eslint"
        versions:
          - ">=10.0.0 <11.0.0"
      - dependency-name: "@eslint/js"
        versions:
          - ">=10.0.0 <11.0.0"
    commit-message:
      prefix: ":robot:"
      include: "scope"
    labels:
      - "dependencies"
      - "nodejs"
      - "frontend"

  # 4. Docker Base Image
  - package-ecosystem: "docker"
    directory: "/app/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    target-branch: main
    commit-message:
      prefix: ":seedling:"
      include: "scope"
    labels:
      - "backend"
      - "docker"
      - "frontend"

  
