apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base
images:
  - name: docker.io/agslima/app-stayhealthy-backend
    digest: sha256:1f6ff3e5bafac02cc27aefe364683dc879eb490dfd7e078ad13f83e6a97d3d30
  - name: docker.io/agslima/app-stayhealthy-worker
    digest: sha256:c0ac1074d0bd18d939f1ea70477ee0685ad8999844f15346dca228c7de92df07
  - name: docker.io/agslima/app-stayhealthy-frontend
    digest: sha256:5efd5bd41cd4648001ff1dcc4d630597f7a76e6c36b88acb999c3ce96c62a32c
