apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASS: "change-me-locally"
  DB_NAME: "secure_db"
  JWT_SECRET: "super-secure-secret"
  ADMIN_USER: "admin"
  ADMIN_PASS: "admin123"
