services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    volumes:
      - client-dist:/app/dist

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
      LOG_LEVEL: info
      CORS_ORIGIN: ${CORS_ORIGIN}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      CLIENT_DIST_PATH: ../client/dist
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    volumes:
      - client-dist:/app/client/dist
    depends_on:
      - frontend
      - postgres
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  client-dist:
  pgdata:

