apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      containers:
      - name: app
        # The CI pipeline will update this tag
        image: agslima/software-delivery-pipeline:latest 
        ports:
        - containerPort: 3000
