apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signature
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  rules:
    - name: require-image-signature
      match:
        any:
          - resources:
              kinds: 
                - Deployment
                - Pod
              namespaces:
                - prod
                - production
      verifyImages:
        - imageReferences:
            # Use wildcards to avoid the index.docker.io vs docker.io trap
            - "*/agslima/app-stayhealthy-backend*"
            - "*/agslima/app-stayhealthy-worker*"
            - "*/agslima/app-stayhealthy-frontend*"
          failureAction: Enforce
          attestors:
            - entries:
                - keyless:
                    issuer: "https://token.actions.githubusercontent.com"
                    # subjectRegExp: "^https://github.com/agslima/app-stayhealthy-pipeline/.github/workflows/ci-release-gate.yml@refs/tags/v.+$"
                    rekor:
                      url: "https://rekor.sigstore.dev"
    
