apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signature
  annotations:
    policies.kyverno.io/title: Verify image signature (keyless)
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: critical
    pod-policies.kyverno.io/autogen-controllers: Deployment,StatefulSet,DaemonSet,Job,CronJob
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  rules:
    - name: require-image-signature
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["prod", "production"]
      verifyImages:
        - imageReferences:
            - "docker.io/agslima/app-stayhealthy-backend@*"
            - "docker.io/agslima/app-stayhealthy-worker@*"  
            - "docker.io/agslima/app-stayhealthy-frontend@*"
            - "index.docker.io/agslima/app-stayhealthy-backend@*"
            - "index.docker.io/agslima/app-stayhealthy-worker@*"  
            - "index.docker.io/agslima/app-stayhealthy-frontend@*"
          failureAction: Enforce
          attestors:
            - entries:
                - keyless:
                    issuer: "https://token.actions.githubusercontent.com"
                    subjectRegExp: "^https://github.com/agslima/software-delivery-pipeline/.github/workflows/ci-release-gate\.yml@refs/tags/v.*$"
                    rekor:
                      url: "https://rekor.sigstore.dev"
