#!/bin/bash

# ==============================================================================
# LOCAL DEVELOPMENT SETUP SCRIPT
# ==============================================================================
# This script initializes the environment variables and secret files required
# to run the application locally using Docker Compose.
#
# Quick Start:
#
#   chmod +x app/setup-dev.sh
#   ./app/scripts/setup-dev.sh
#
# Ensure you add the following to your .gitignore to prevent
# committing these local secrets:
#
#  /secrets/
#  .env
#
# This script is idempotent; running it multiple times will not overwrite
# existing secret files or the .env file.
#
# ==============================================================================

set -e # Exit on error

# 1. Define Directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# APP_DIR is the parent directory (app/) where docker-compose.yml lives
APP_DIR="$(dirname "$SCRIPT_DIR")"
SECRETS_DIR="${APP_DIR}/secrets"
ENV_FILE="${APP_DIR}/.env"

echo "🔧 Initializing Local Development Environment..."
echo "   -> App Directory detected: ${APP_DIR}"

# 2. Create Secrets Directory
if [[ ! -d "$SECRETS_DIR" ]]; then
    echo "   -> Creating secrets directory: secrets/"
    mkdir -p "$SECRETS_DIR"
else
    echo "   -> Secrets directory exists. Skipping."
fi
chmod 755 "$SECRETS_DIR"

# random_hex generates a hexadecimal string representing the requested number of random bytes and writes it to stdout.
# bytes is the number of bytes to generate; output contains 2*bytes hex characters. If secure randomness is unavailable, a non-cryptographic timestamp is used as a fallback.
random_hex() {
    local bytes=$1
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$bytes"
    elif [[ -r /dev/urandom ]]; then
        head -c "$bytes" /dev/urandom | od -An -tx1 | tr -d ' \n'
    else
        echo "No cryptographically secure random source available" >&2  
        return 1
    fi
}

# generate_secret writes a random hexadecimal secret to SECRETS_DIR/<filename> if the file does not exist and ensures the file is chmod 644; the optional second argument sets the byte length of the secret (default 32).
generate_secret() {
    local filename=$1
    local bytes=${2:-32}
    local filepath="${SECRETS_DIR}/${filename}"

    if [[ ! -f "$filepath" ]]; then
        echo "   -> Generating secret: ${filename}"
        printf "%s" "$(random_hex "$bytes")" > "$filepath"
    else
        echo "   -> Secret exists: ${filename} (Skipping)"
    fi
    chmod 644 "$filepath"
}

# Generate random local secrets
generate_secret "db_pass.txt" 16
generate_secret "admin_pass.txt" 16
generate_secret "jwt_secret.txt" 32
generate_secret "data_encryption_key.txt" 32

# 4. Generate .env File
if [[ ! -f "$ENV_FILE" ]]; then
    echo "   -> Creating default .env file..."
    cat <<EOF > "$ENV_FILE"
# Local Development Environment Variables
# Generated by setup-dev.sh

# Logging
LOG_LEVEL=info 

# Docker Compose Project Name
COMPOSE_PROJECT_NAME=my_app_dev

# Database Config (Non-sensitive)
DB_USER=postgres
DB_NAME=prescriptions_db

# Admin Config
ADMIN_USER=admin

# Access Tokens
ACCESS_TOKEN_TTL_MINUTES=15

# TLS enforcement (optional)
ENFORCE_TLS=false
TRUST_PROXY=

# Encryption key rotation (optional)
DATA_ENCRYPTION_KEY_ID=v1
DATA_ENCRYPTION_KEYS=

# Audit pipeline
AUDIT_SINK=db
AUDIT_PII_REDACTION=none

# Observability
METRICS_ENABLED=false
METRICS_PATH=/metrics
METRICS_AUTH_TOKEN=

# OIDC (Optional)
OIDC_ENABLED=false
OIDC_REQUIRED=false
OIDC_ISSUER=
OIDC_AUDIENCE=
OIDC_JWKS_URI=
OIDC_EMAIL_CLAIM=email
OIDC_ROLE_CLAIM=roles
OIDC_MFA_REQUIRED_ROLES=doctor,admin
OIDC_REQUIRED_AMR=mfa
OIDC_REQUIRED_ACR=
OIDC_CLOCK_TOLERANCE_SECONDS=5

# NOTE: Passwords and Secrets are loaded from ./secrets/ directory
# by docker-compose.yml automatically.
EOF
else
    echo "   -> .env file exists. Skipping."
fi

echo "✅ Setup Complete!"
echo "🚀 You can now run: cd app && docker-compose up --build"
echo "🗃️  Local backend bootstrap command: cd app/server && npm run db:bootstrap"
