#!/bin/bash

# ==============================================================================
# LOCAL DEVELOPMENT SETUP SCRIPT
# ==============================================================================
# This script initializes the environment variables and secret files required
# to run the application locally using Docker Compose.
#
# Quick Start:
#
#   chmod +x app/setup-dev.sh
#   ./app/scripts/setup-dev.sh
#
# Ensure you add the following to your .gitignore to prevent
# committing these local secrets:
#
#  /secrets/
#  .env
#
# This script is idempotent; running it multiple times will not overwrite
# existing secret files or the .env file.
#
# ==============================================================================

set -e # Exit on error

# 1. Define Directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# APP_DIR is the parent directory (app/) where docker-compose.yml lives
APP_DIR="$(dirname "$SCRIPT_DIR")"
SECRETS_DIR="${APP_DIR}/secrets"
ENV_FILE="${APP_DIR}/.env"

echo "🔧 Initializing Local Development Environment..."
echo "   -> App Directory detected: ${APP_DIR}"

# 2. Create Secrets Directory
if [ ! -d "$SECRETS_DIR" ]; then
    echo "   -> Creating secrets directory: secrets/"
    mkdir -p "$SECRETS_DIR"
else
    echo "   -> Secrets directory exists. Skipping."
fi

# 3. Generate Secret Files (Idempotent: Won't overwrite existing)
generate_secret() {
    local filename=$1
    local default_value=$2
    local filepath="${SECRETS_DIR}/${filename}"

    if [ ! -f "$filepath" ]; then
        echo "   -> Generating secret: ${filename}"
        printf "%s" "$default_value" > "$filepath"
    else
        echo "   -> Secret exists: ${filename} (Skipping)"
    fi
}

# Define your default local secrets here
generate_secret "db_pass.txt" "local_postgres_password"
generate_secret "admin_pass.txt" "local_admin_password"
generate_secret "jwt_secret.txt" "local_development_secret_key_123"

# 4. Generate .env File
if [ ! -f "$ENV_FILE" ]; then
    echo "   -> Creating default .env file..."
    cat <<EOF > "$ENV_FILE"
# Local Development Environment Variables
# Generated by setup-dev.sh

# Logging
LOG_LEVEL=info 

# Docker Compose Project Name
COMPOSE_PROJECT_NAME=my_app_dev

# Database Config (Non-sensitive)
DB_USER=postgres
DB_NAME=prescriptions_db

# Admin Config
ADMIN_USER=admin

# NOTE: Passwords and Secrets are loaded from ./secrets/ directory
# by docker-compose.yml automatically.
EOF
else
    echo "   -> .env file exists. Skipping."
fi

echo "✅ Setup Complete!"
echo "🚀 You can now run: cd app && docker-compose up --build"